### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by taigw** [HiLab-git/MyoPS2020#1]
Fix typos in readme, and update other files if needed.

**Comment by AManHasNoName12138** [comment]
Permission denied. I pushed README.md on two machines and both failed. I don’t know if it’s my problem.
```
ERROR: Permission to HiLab-git/MyoPS2020.git denied to AManHasNoName12138.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
```

**Comment by taigw** [comment]
I have updated your permission. Please try again.

**Comment by AManHasNoName12138** [comment]
OK. I've updated README.
